version: '3'

services:
  nginx:
    container_name: nginx
    tty: true
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
    build:
      context: ./nginx
    ports:
      - "8080:80"
    command: /bin/sh -c "exec nginx -g 'daemon off;'"
    depends_on:
      - app
    networks:
      - node-nginx-app

  app:
    container_name: app
    tty: true
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s sh -c "npm install && node index.js"
    build:
      context: ./app
    volumes:
      - ./app:/usr/src/app
    networks:
      - node-nginx-app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    networks:
      - node-nginx-app
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root

networks:
  node-nginx-app:
    driver: bridge